controllers/CalculatorController.php
<?php
namespace app\controllers;

use app\libs\Calculator;
use app\models\AdditionalWorks;
use app\models\Comunications;
use app\models\Emails;
use app\models\Files;
use app\models\Percent;
use app\models\Phones;
use app\models\Promotions;
use app\models\Settings;
use yii\db\Exception;
use yii\helpers\Url;
use yii\web\Response;
use Yii;
use yii\web\Controller;

class CalculatorController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @return string|Response
     */
    public function actionCalculationAjax()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        if(/*Yii::$app->request->isAjax &&*/ Yii::$app->request->isGet)
        {
            $calculator = new Calculator();
            switch(Yii::$app->request->get('data')['lamination'])
            {
                case 0:
                    $data['color'] = 'w';
                    break;
                case 1:
                    $data['color'] = 'c';
                    break;
            }
            $data['contentSliderHeight'] = Yii::$app->request->get('data')['contentSliderHeight'];
            $data['contentSliderHeightRight'] = Yii::$app->request->get('data')['contentSliderHeightRight'];
            $data['contentSliderWidth'] = Yii::$app->request->get('data')['contentSliderWidth'];
            $data['contentSliderWidthTop'] = Yii::$app->request->get('data')['contentSliderWidthTop'];
            $data['montaj'] = Yii::$app->request->get('data')['montaj'];
            $data['moskit'] = Yii::$app->request->get('data')['moskit'];
            $data['musor'] = Yii::$app->request->get('data')['musor'];
            $data['otkos'] = Yii::$app->request->get('data')['otkos'];
            $data['typeWindow'] = Yii::$app->request->get('data')['typeWindow'];
            $data['furnituraVal'] = Yii::$app->request->get('data')['characteristicsWindow']['furnituraVal'];
            $data['otlivVal'] = Yii::$app->request->get('data')['characteristicsWindow']['otlivVal'];
            $data['podokonnikVal'] = Yii::$app->request->get('data')['characteristicsWindow']['podokonnikVal'];
            $data['profileVal'] = Yii::$app->request->get('data')['characteristicsWindow']['profileVal'];
            $data['steklopaketVal'] = Yii::$app->request->get('data')['characteristicsWindow']['steklopaketVal'];
            if(empty($data['profileVal']))
            {
                return $this->asJson(['warning' => 'Выберите профиль! Для просчета данных калькулятору нужны минимальные данные, такие, как фурнитура, стеклопакет, профиль.']);
            }
            if(empty($data['steklopaketVal']))
            {
                return $this->asJson(['warning' => 'Выберите стеклопакет! Для просчета данных калькулятору нужны минимальные данные, такие, как фурнитура, стеклопакет, профиль.']);
            }
            if($data['typeWindow'] == "1g")
            {
                $data['furnituraVal'] = 'ax';
            }
            if(empty($data['furnituraVal']))
            {
                return $this->asJson(['warning' => 'Выберите фурнитуру! Для просчета данных калькулятору нужны минимальные данные, такие, как фурнитура, стеклопакет, профиль.']);
            }
            // формируем название таблицы
            if($data['typeWindow'] == '1b1g')
            {
                $calculator->typeWindow = 1;
                $fileName[0] = '1b,'.$data['color'];
                $fileName[1] = '1g,'.$data['color'];
                $tabName[0] = '1b,'
                    .$data['profileVal'].','
                    .$data['furnituraVal'].','
                    .$data['color'].','
                    .$data['steklopaketVal'];
                $tabName[1] = '1g,'
                    .$data['profileVal'].','
                    .$data['furnituraVal'].','
                    .$data['color'].','
                    .$data['steklopaketVal'];
            }
            elseif($data['typeWindow'] == '1b2gp')
            {
                $calculator->typeWindow = 1;
                $fileName[0] = '1b,'.$data['color'];
                $fileName[1] = '2gp,'.$data['color'];
                $tabName[0] = '1b,'
                    .$data['profileVal'].','
                    .$data['furnituraVal'].','
                    .$data['color'].','
                    .$data['steklopaketVal'];
                $tabName[1] = '2gp,'
                    .$data['profileVal'].','
                    .$data['furnituraVal'].','
                    .$data['color'].','
                    .$data['steklopaketVal'];
            }
            else
            {
                $calculator->typeWindow = 0;
                $fileName[0] = $data['typeWindow'].','.$data['color'];
                $tabName[0] = $data['typeWindow'].','
                    .$data['profileVal'].','
                    .$data['furnituraVal'].','
                    .$data['color'].','
                    .$data['steklopaketVal'];
            }
            $file = [];
            foreach($fileName as $key => $item)
            {
                $file[$key] = Files::find()->where(['name' => $item])->limit(1)->all()[0];
            }

            if(count($file) > 0)
            {
                $fileUrl = [];
                foreach($file as $key => $item)
                {
                    $fileUrl[$key] = Url::to($item->path) . $item->name . $item->extension; // путь к файлу
                }

                $excelArray = $calculator->getFromExcel($fileUrl, $tabName); // получаем массив с excel
                if($excelArray['warning'])
                {
                    return $this->asJson(['warning' => [[$excelArray['warning']]]]); // если не найден файл
                }
                $priceWindowUSA = $calculator->getWindowPrice( // получаю цену за окно
                    $data['contentSliderWidth'],
                    $data['contentSliderHeight'],
                    $data['contentSliderWidthTop'],
                    $data['contentSliderHeightRight'],
                    $excelArray
                );
                $sillTotalPriceUA = 0;
                if(isset($data['podokonnikVal']) && !empty($data['podokonnikVal'])) // +
                {
                    $sillTotalPriceUA = $calculator->getSill($data['podokonnikVal'], $data['contentSliderWidth'], $data['contentSliderHeight'], $data['contentSliderHeightRight'], $data['contentSliderWidthTop']); // формироуем цену подоконника
                }
                $outflowsTotalPriceUA = 0;
                if(isset($data['otlivVal']) && !empty($data['otlivVal'])) // +
                {
                    $outflowsTotalPriceUA = $calculator->getOutflows($data['otlivVal'], $data['contentSliderWidth'], $data['contentSliderHeight'], $data['contentSliderHeightRight'], $data['contentSliderWidthTop']); // формируем цену отлива
                }
                $additionalWorksArr = []; // получаем список настроек
                $additionalWorks = AdditionalWorks::find()->all();
                foreach($additionalWorks as $additionalWork)
                {
                    $additionalWorksArr[$additionalWork->name] = $additionalWork->value;
                }
                unset($additionalWorks);
                $slopesTotalPriceUA = 0;
                if($data['otkos'])
                {
                    $slopesTotalPriceUA = $calculator->getSlopes(
                        $data['contentSliderHeight'],
                        $data['contentSliderWidth'],
                        $data['contentSliderWidthTop'],
                        $data['contentSliderHeightRight'],
                        $additionalWorksArr['slopes']); // считаем otkosi
                }
                $windowInstalationTotalPrice = 0;
                if($data['montaj']) //+
                {
                    $windowInstalationTotalPrice = $calculator->getWindowInstalation(
                        $data['contentSliderHeight'],
                        $data['contentSliderWidth'],
                        $data['contentSliderWidthTop'],
                        $data['contentSliderHeightRight'],
                        $additionalWorksArr['windowInstalation']); // считаем montazh
                }
                $mosquitoNet = 0;
                if($data['moskit'])
                {
                    $mosquitoNet =$additionalWorksArr['mosquitoNet']; // считаем москитную сетку
                }
                $gorbageRemoval = 0;
                if($data['musor'])
                {
                    $gorbageRemoval = $additionalWorksArr['gorbageRemoval']; // считаем мусоо
                }
                // получаем массив настроек
                $settingArr = [];
                $setting = Settings::find()->all();
                foreach($setting as $item)
                {
                    $settingArr[$item->name] = $item->value;
                }
                unset($setting);
                // скидки и акции
                $promotionArr = [];
                $promotins = Promotions::find()->all();
                foreach($promotins as $promotin)
                {
                    $promotionArr[$promotin->name] = $promotin->value;
                }
                unset($promotins);
                // подсчитываем всю сумму
                if(!isset($settingArr["dollarExchangeRate"]) || $settingArr["dollarExchangeRate"] <= 0)
                {
                    $settingArr["dollarExchangeRate"] = 1;
                }
                $priceWindowUAOrigin = $priceWindowUSA * $settingArr["dollarExchangeRate"];
                $priceWindowUA = round($priceWindowUAOrigin - (($priceWindowUAOrigin / 100) * (integer)$promotionArr['discountOnWindows']), 0); // стоимость окна с учетом процента скидки на окна

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Product;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect('/admin');
        }


        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        $users = User::findOne(1);
//        dd($users);

        return $this->render('about', compact('users', 'products'));
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>

<?php dump($users) ?>
<?php echo count($users->products) ?>
<?php dump($users->products) ?>
<?php //dump($products) ?>
<div class="site-about">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
//
//use yii\helpers\Html;
//use yii\helpers\Url;
//?>
<!---->
<!--<section class="calculator_page">-->
<!--    <div class="calculator_wrapper">-->
<!--        <div class="calc_head">-->
<!--            <h1>Калькулятор окон</h1>-->
<!--            <p class="calc_steps_name">шаг 1: Выберите конструкцию</p>-->
<!--            <div class="calc_type_of_construction">-->
<!--                --><?//= Html::img('img/type_of_win1.png', ['id' => 'window__0']) ?>
<!--                --><?//= Html::img('img/type_of_win2.png', ['id' => 'window__1']) ?>
<!--                --><?//= Html::img('img/type_of_win3.png', ['id' => 'window__01']) ?>
<!--                --><?//= Html::img('img/type_of_win4.png', ['id' => 'window__0_1']) ?>
<!--                --><?//= Html::img('img/type_of_win5.png', ['id' => 'window__010']) ?>
<!--                --><?//= Html::img('img/type_of_win6.png', ['id' => 'window__101']) ?>
<!--                --><?//= Html::img('img/type_of_win7.png', ['id' => 'window__0110']) ?>
<!--                --><?//= Html::img('img/type_of_win8.png', ['id' => 'window__d0', 'class' => 'balcon_constr']) ?>
<!--                --><?//= Html::img('img/type_of_win9.png', ['id' => 'window__d01', 'class' => 'balcon_constr']) ?>
<!--            </div>-->
<!---->
<!--            <div class="need_other_construction">Нужна другая конструкция?</div>-->
<!--        </div>-->
<!---->
<!--        <div class="calculator_body">-->
<!--            <p class="calc_steps_name">шаг 2: Выберите основные комплектующие</p>-->
<!--            <div class="calc_characteristics_left">-->
<!--                <div class="calc_characteristics_left_item" id="profileVal">-->
<!--                    <span class="name_calc_left_item">Профиль</span>-->
<!--                    <i class="fa fa-angle-down" aria-hidden="true"></i>-->
<!--                    <ul class="notactive">-->
<!--                        <li data-value="lider">Lider</li>-->
<!--                        <li data-value="B58">B58</li>-->
<!--                        <li data-value="B70">B70</li>-->
<!--                    </ul>-->
<!---->
<!--                    <select name="profile" id="profile" class="notactive">-->
<!--                        <option value="lider">Lider</option>-->
<!--                        <option value="B58">B58</option>-->
<!--                        <option value="B70">B70</option>-->
<!--                    </select>-->
<!--                </div>-->
<!---->
<!--                <div class="calc_characteristics_left_item" id="steklopaketVal">-->
<!--                    <span class="name_calc_left_item">Стеклопакет</span>-->
<!--                    <i class="fa fa-angle-down" aria-hidden="true"></i>-->
<!--                    <ul class="notactive">-->
<!--                        <li data-value="Однокамерный">Однокамерный</li>-->
<!--                        <li data-value="Двухкамер. + энерго">Двухкамер. + энерго</li>-->
<!--                        <li data-value="Двухкамер. + мультифунк.">Двухкамер. + мультифунк.</li>-->
<!--                    </ul>-->
<!---->
<!--                    <select name="steklopaket" id="steklopaket" class="notactive">-->
<!--                        <option value="Однокамерный">Однокамерный</option>-->
<!--                        <option value="Двухкамер. + энерго">Двухкамер. + энерго</option>-->
<!--                        <option value="Двухкамер. + мультифунк.">Двухкамер. + мультифунк.</option>-->
<!--                    </select>-->
<!--                </div>-->
<!---->
<!--                <div class="calc_characteristics_left_item" id="furnituraVal">-->
<!--                    <span class="name_calc_left_item">Фурнитура</span>-->
<!--                    <i class="fa fa-angle-down" aria-hidden="true"></i>-->
<!--                    <ul class="notactive">-->
<!--                        <li data-value="Axor">Axor (Украина)</li>-->
<!--                        <li data-value="Siegenia">Siegenia (Германия)</li>-->
<!--                    </ul>-->
<!---->
<!--                    <select name="furnitura" id="furnitura" class="notactive">-->
<!--                        <option value="Axor">Axor (Украина)</option>-->
<!--                        <option value="Siegenia">Siegenia (Германия)</option>-->
<!--                    </select>-->
<!--                </div>-->
<!---->
<!--                <div class="calc_characteristics_left_item" id="podokonnikVal">-->
<!--                    <span class="name_calc_left_item">Подоконник</span>-->
<!--                    <i class="fa fa-angle-down" aria-hidden="true"></i>-->
<!--                    <ul class="notactive">-->
<!--                        <li data-value="1">1</li>-->
<!--                        <li data-value="2">2</li>-->
<!--                        <li data-value="3">3</li>-->
<!--                        <li data-value="4">4</li>-->
<!--                    </ul>-->
<!---->
<!--                    <select name="podokonnik" id="podokonnik" class="notactive">-->
<!--                        <option value="1">1</option>-->
<!--                        <option value="2">2</option>-->
<!--                        <option value="3">3</option>-->
<!--                        <option value="4">4</option>-->
<!--                    </select>-->
<!--                </div>-->
<!---->
<!--                <div class="calc_characteristics_left_item" id="otlivVal">-->
<!--                    <span class="name_calc_left_item">Отлив</span>-->
<!--                    <i class="fa fa-angle-down" aria-hidden="true"></i>-->
<!--                    <ul class="notactive">-->
<!--                        <li data-value="1">1</li>-->
<!--                        <li data-value="2">2</li>-->
<!--                        <li data-value="3">3</li>-->
<!--                        <li data-value="4">4</li>-->
<!--                    </ul>-->
<!---->
<!--                    <select name="otliv" id="otliv" class="notactive">-->
<!--                        <option value="1">1</option>-->
<!--                        <option value="2">2</option>-->
<!--                        <option value="3">3</option>-->
<!--                        <option value="4">4</option>-->
<!--                    </select>-->
<!--                </div>-->
<!--            </div>-->
<!---->
<!--            <p class="calc_steps_name">шаг 3: укажите размер и дополнительные комплектующие</p>-->
<!---->
<!---->
<!--            <div class="calc_size_characteristics">-->
<!--                <div id="width_slider_balcon_top" class="notactive">-->
<!--                    <div class="width_slider_input_wrap">-->
<!--                        <input type="text" id="contentSliderWidthTop"></input>-->
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--                <div id="height_slider">-->
<!--                    <div class="height_slider_input_wrap">-->
<!--                        <input type="text" id="contentSliderHeight"></input>-->
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--                <div id="width_slider">-->
<!--                    <div class="width_slider_input_wrap">-->
<!--                        <input type="text" id="contentSliderWidth"></input>-->
<!--                    </div>-->
<!--                    <span class="coordinate_start">0</span>-->
<!--                </div>-->
<!---->
<!--                <div id="height_slider_balcon_right" class="notactive">-->
<!--                    <div class="height_slider_input_wrap">-->
<!--                        <input type="text" id="contentSliderHeightRight"></input>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="win_in_calc" style="background-image: url('img/win_in_calc_1.png');"></div>-->
<!--            </div>-->
<!---->
<!--            <div class="calc_characteristics_right">-->
<!--                <div class="calc_characteristics_right_item">-->
<!--                    <p>Монтаж</p>-->
<!---->
<!--                    <div class="select_char">-->
<!--                        <label>-->
<!--                            <input class="radio" type="radio" value="1" name="montaj" checked="checked">-->
<!--                            <span class="radio-custom"></span>-->
<!--                            <span class="label">да</span>-->
<!--                        </label>-->
<!---->
<!--                        <label>-->
<!--                            <input class="radio" type="radio" value="0" name="montaj">-->
<!--                            <span class="radio-custom"></span>-->
<!--                            <span class="label">нет</span>-->
<!--                        </label>-->
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--                <div class="calc_characteristics_right_item">-->
<!--                    <p>Москитная сетка</p>-->
<!---->
<!--                    <div class="select_char">-->
<!--                        <label>-->
<!--                            <input class="radio" type="radio" name="moskit" value="1" checked="checked">-->
<!--                            <span class="radio-custom"></span>-->
<!--                            <span class="label">да</span>-->
<!--                        </label>-->
<!---->
<!--                        <label>-->
<!--                            <input class="radio" type="radio" value="0" name="moskit">-->
<!--                            <span class="radio-custom"></span>-->
<!--                            <span class="label">нет</span>-->
<!--                        </label>-->
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--                <div class="calc_characteristics_right_item">-->
<!--                    <p>Ламинация</p>-->
<!---->
<!--                    <div class="select_char">-->
<!--                        <label>-->
<!--                            <input class="radio" type="radio" value="1" name="lamination" checked="checked">-->
<!--                            <span class="radio-custom"></span>-->
<!--                            <span class="label">да</span>-->
<!--                        </label>-->
<!---->
<!--                        <label>-->
<!--                            <input class="radio" type="radio" value="0" name="lamination">-->
<!--                            <span class="radio-custom"></span>-->
<!--                            <span class="label">нет</span>-->
<!--                        </label>-->
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--                <div class="calc_characteristics_right_item">-->
<!--                    <p>Откосы</p>-->
<!---->
<!--                    <div class="select_char">-->
<!--                        <label>-->
<!--                            <input class="radio" type="radio" value="1" name="otkos" checked="checked">-->
<!--                            <span class="radio-custom"></span>-->
<!--                            <span class="label">да</span>-->
<!--                        </label>-->
<!---->
<!--                        <label>-->
<!--                            <input class="radio" type="radio" value="0" name="otkos">-->
<!--                            <span class="radio-custom"></span>-->
<!--                            <span class="label">нет</span>-->
<!--                        </label>-->
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--                <div class="calc_characteristics_right_item">-->
<!--                    <p>Вынос мусора</p>-->
<!---->
<!--                    <div class="select_char">-->
<!--                        <label>-->
<!--                            <input class="radio" type="radio" value="1" name="musor" checked="checked">-->
<!--                            <span class="radio-custom"></span>-->
<!--                            <span class="label">да</span>-->
<!--                        </label>-->
<!---->
<!--                        <label>-->
<!--                            <input class="radio" type="radio" value="0" name="musor">-->
<!--                            <span class="radio-custom"></span>-->
<!--                            <span class="label">нет</span>-->
<!--                        </label>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!---->
<!---->
<!--            <div class="calc_price">-->
<!--                Узнать цену-->
<!--            </div>-->
<!---->
<!--            <div class="calculated_price_block notactive">-->
<!--                <div class="calculated_full_price">-->
<!--                    <p class="calculated_price_block_name">Полная стоимость</p>-->
<!--                    <p class="calculated_price_block_value">2584 грн</p>-->
<!--                </div>-->
<!---->
<!--                <div class="calculated_sale">-->
<!--                    <p class="calculated_price_block_name">Скидка</p>-->
<!--                    <p class="calculated_price_block_value">10%</p>-->
<!--                </div>-->
<!---->
<!--                <div class="calculated_price_with_sale">-->
<!--                    <p class="calculated_price_with_sale_name">Итоговая стоимость</p>-->
<!--                    <p class="calculated_price_with_sale_value">2000 грн</p>-->
<!--                </div>-->
<!--            </div>-->
<!---->
<!--            <div class="calculator_recall_me notactive">-->
<!--                Перезвоните мне-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!---->
<!--</section>-->
<!---->
<!---->
<!--<script>-->
<!--    var calculator = {indix: {-->
<!--        url: '--><?//= Url::to(["/calculator/calculation-ajax"]) ?>//'
//    }
//    };
//</script>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>